export const POSTS_REQUESTED = 'POSTS_REQUESTED';
export const POSTS_RECEIVED = 'POSTS_RECEIVED';
export const POSTS_FAILED = 'POSTS_FAILED';

export const AUTH_REQUESTED = 'REGISTRATION_REQUESTED';
export const AUTH_RECEIVED = 'REGISTRATION_RECEIVED';
export const AUTH_FAILED = 'REGISTRATION_FAILED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const REGISTRATION = 'REGISTRATION';
export const AUTHORIZATION = 'AUTHORIZATION';
